language: python
python:
- "3.6"
services:
- mysql

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
#before_script: mysql -e 'CREATE DATABASE test;'
env:
 global:
 - DATABASE_URI='mysql+pymysql://root:wishlists_dev@0.0.0.0:3306/wishlists'
script: 
 - nosetests
#after_success:
# - codecov
#services:
#- mysql
